version: '3.5'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./php-apache
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php-apache/html:/var/www/html/
    ports:
      - 80:80

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbstuff
      MYSQL_USER: dbstuff
      MYSQL_PASSWORD: dbstuff
    ports:
      - "3306:3306"

  phpmyadmin:
    image: arm64v8/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
