# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jgourd/CSC330UT"
  config.vm.box_version = "2024.25.01"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.name = "CSC330-AMD64"
    v.memory = 4096
    v.cpus = 2
    v.customize [ "modifyvm", :id, "--clipboard", "bidirectional" ]
  end

#  config.vm.network "forwarded_port", id: "http", guest: 80, host: 8080
#  config.vm.network "public_network"

  config.vm.provision "shell", inline: "cd ~/Downloads/CSC330UT && git pull", privileged: false
end
